### ISSUE TITLE
Exploratory data analysis: set up and intro to plotting

### ISSUE THREAD

**Issue by aimalz** [lialubit/Redshift#1]
This issue can be closed when there is a Jupyter notebook that:

- [x] reads in zCOSMOS data
- [x] reads in COSMOS data
- [x] plots the distributions of redshifts in each dataset as histograms

**Comment by lialubit** [comment]
I will:

- [x] redo codeacademy last lesson
- [x] setup annaconda
- [x] Install numpy and matplotlib
- [x] make a jupyter notebook
- [x] move on to task listed above

**Comment by lialubit** [comment]
Hello,
Every time I use Jupyter Notebook, after about 15 minutes it stops working and gives me a message saying my kernel has died. 
None of the solutions I have found online have worked (uninstalling Anaconda, etc.) and every time it happens I have to restart my computer. 
How do I fix this?
Thanks

**Comment by aimalz** [comment]
This is great progress!  I have a hunch about your Jupyter issue that I can check later today.  We'll get this sorted out!

**Comment by lialubit** [comment]
![redshift plot 3](https://user-images.githubusercontent.com/34726972/35015889-51a258d4-fb0e-11e7-94b2-be30524b241f.png)

**Comment by aimalz** [comment]
Excellent work, @lialubit!  Let's set some goals for next time to continue the exploratory data analysis:

- [ ] Read up on the magnitude system and photometric colors
- [x] Scale up analysis to more physical quantities (magnitudes and colors)
- [x] Scale up analysis to more galaxies
- [ ] Cross-match galaxies to identify those present in both the spectroscopic and photometric datasets and those present only in the photometric dataset
- [ ] Compare more properties using scatterplots and histograms

**Comment by lialubit** [comment]
Jupyter keeps giving me an error message saying astropy doesn't exist, even thought it worked last time I tried it. Anaconda says it is installed but jupyter still doesn't recognize it. Without it I can't run any graphs, what should I do?

**Comment by lialubit** [comment]
The X match keeps giving me this message:
<img width="1010" alt="screen shot 2018-01-30 at 10 34 52 am" src="https://user-images.githubusercontent.com/34726972/35574988-43c6e284-05a9-11e8-8132-921f4b0b5af3.png">

**Comment by aimalz** [comment]
Re: Jupyter, I've bumped into a few causes of that error and can show you the simplest ways to troubleshoot it later today (and hopefully the root of the problem is one that's not too hard to solve).

Re: XMatch, try changing the table names to J/ApJS/184/218/table3 and II/284/cosmos instead of the URLs.

**Comment by aimalz** [comment]
Though there's (always) still more to learn and more to do, I think this issue can be closed since you've figured out how to get and plot data, and other problems will be addressed in their own issues.  Great job, @lialubit!
