### ISSUE TITLE
Cross-matching data

### ISSUE THREAD

**Issue by aimalz** [lialubit/Redshift#3]
EDIT: I'm breaking this up into three issues because it's getting complicated!

You have magnitudes in many photometric filters along with photometric redshifts for the whole COSMOS dataset and spectroscopic redshifts and i-band magnitudes for the zCOSMOS dataset.  When we talk about support between datasets, we need to distinguish between galaxies that are in both COSMOS and zCOSMOS, galaxies that are only in COSMOS, and galaxies that are only in zCOSMOS, and we need to define what data we're even interested in, namely the photometric magnitudes.  (Theoretically, there shouldn't be any galaxies in zCOSMOS but not COSMOS, but because the folks who made the COSMOS catalog omitted some very noisy data points, there are some.)  So, we need to construct two datasets: the magnitudes in all filters and the redshifts of the zCOSMOS galaxies that are also in COSMOS and the magnitudes in all filters for the COSMOS galaxies that are not in zCOSMOS.  To start, we have to perform a cross-match; I think we may have already done this but possibly lost track of the results due to uninformative file names, so here it is again.

- [x] Try out the [cross-matching tool](http://cdsxmatch.u-strasbg.fr/xmatch) to identify galaxies that are in both COSMOS and zCOSMOS and save the data to a file with an unforgettable name

If we already did this, all you have to do is rename the file.

**Comment by lialubit** [comment]
The cross matching tool gives me an ascii file. I have been using fits files, and I don't think my code works for any non fits file. Is there any way to make the cross matching tool give me a fits file? I cannot find anything online for this.

**Comment by aimalz** [comment]
Converting data types can indeed get very messy, and I have a lot to learn, too.  Try [this](https://gist.github.com/aimalz/26b995cf77f3d1999b8f6669dc1294fb) out and let me know if it doesn't help.

**Comment by aimalz** [comment]
Awesome job!
