### ISSUE TITLE
Selecting data

### ISSUE THREAD

**Issue by aimalz** [lialubit/Redshift#4]
Now it's time to find the photometric magnitudes for the zCOSMOS galaxies, but they're mixed into the COSMOS dataset, which contains a lot of galaxies that aren't in zCOSMOS at all.  Now that you have the cross-match results, you know the (COSMOS ID number, zCOSMOS ID number) pairs.  The next step is to pick out the COSMOS data for the zCOSMOS galaxies and separate it from the COSMOS data for galaxies not in the zCOSMOS dataset.  This is also a good time to remove the placeholders for bad measurements -- galaxies with -9999 for a photometric magnitude and/or 0.0 for redshift.

Since @marin-hyatt also has some similar tasks on the horizon, I'll suggest you join forces and learn together.  I've done this with `pandas` `DataFrame` objects, but it can be done with `numpy` `array` objects, too.

**Comment by lialubit** [comment]
We both finished this, so I'm going to close this issue. Yay
