### ISSUE TITLE
Cleaning Up and Moving On

### ISSUE THREAD

**Issue by lialubit** [lialubit/Redshift#5]
- [x] Upload cosmos doc with UNLIMITED cosmos
- [x] Do a diagnostic plot to find what abnormal values there are in cosmos and zcosmos
- [x] Remove all abnormal values from cosmos and from zcosmos
- [x] Remove all abnormal values from cross match
- [x] Remove duplicates from crossmatch
- [x] Update everything to make sure these NEW AND IMPROVED docs (cosmos, zcosmos, cross match)
- [ ] Compare zcosmos-and-cosmos and cosmos: redshift, magnitudes
- [x] Read documents listed in google doc
- [x] Clean Up - Make comments for more complicated commands/ones you might forget, etc. 
- [x] BE HAPPY

**Comment by lialubit** [comment]
Today (4/1) I did #1, #2, #3, and #4. I got a couple error messages that I am trying to understand. I will keep searching for the solutions to these (which only affect part of each command). Ultimately though, each of the methods I have tried have worked, with some mini issues but none that have to do with the overall method. YAY. :-)

**Comment by aimalz** [comment]
Great work @lialubit!  I'm not sure what's causing the error in cell 100 either, but I think you're right that it's not mission critical.  The important columns are the magnitudes through each filter and the photometric redshift, so maybe just focus on those for the diagnostic plots.

**Comment by lialubit** [comment]
I am having trouble with the comparison in step #7. Its giving me an error saying "max must be larger than min in range parameter".

**Comment by aimalz** [comment]
Sorry for not seeing your comment sooner.  I'm glad this setback hasn't affected your completion of the final item in the checklist!  We'll work together to debug this later today.

**Comment by lialubit** [comment]
I had a bunch of computer complications but a few days ago I was finally able to use this again and I'm a bit confused with the responses I am getting from Jupyter. 
When I try to find where the NaN is is get <function numpy.core.multiarray.where>, and I can't find anything useful about this online. 
What is this trying to tell me?

**Comment by aimalz** [comment]
I'm not sure what information you have in front of you and don't see any recently updated files in the repository.  We'll take a look at it later today, but questions about code should always be accompanied by the code in question, preferably as a link to the file in the repository.

**Comment by aimalz** [comment]
Let's move on from here and start some new issues, for science!

**Comment by lialubit** [comment]
YAY
